name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet fpdf2 arabic-reshaper python-bidi

      - name: Initialize Flet Project & Build APK
        run: |
          # إنشاء مشروع جديد بالهيكل القياسي
          flet create falcon_app
          
          # نقل ملف الـ main.py الخاص بك ليكون هو ملف التشغيل الأساسي داخل المجلد
          cp main.py falcon_app/src/main.py
          
          # الانتقال لمجلد المشروع وبناء ملف الـ APK
          cd falcon_app
          flutter pub get
          flet build apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: falcon_app/build/app/outputs/flutter-apk/app-release.apk